default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 
  host: 127.0.0.1
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: docker_demo_development

test:
  <<: *default
  database: docker_demo_test

production:
  <<: *default
  database: docker_demo_production